blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord Channel for Resideo
    url: https://discord.gg/8fpZA4S
    about: Please ask and answer questions here.
  - name: Homebridge-Resideo - Pull Requests
    url: https://github.com/donavanbecker/homebridge-resideo/pulls
    about: Please report security vulnerabilities here.
